import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-hello-world-auto-generated',
  templateUrl: './hello-world-auto-generated.component.html',
  styleUrls: ['./hello-world-auto-generated.component.css']
})
export class HelloWorldAutoGeneratedComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
