import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,home,forest }) {
  console.log(home,forest)
  return (
    <html lang="en">
   
      <body className={inter.className}>
  
        {children}
        {home}
        {forest}
        </body>
    </html>
  )
}
