import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import { HelloWorldComponent } from './components/hello-world/hello-world.component';
import { HelloWorldAutoGeneratedComponent } from './components/hello-world-auto-generated/hello-world-auto-generated.component';
@NgModule({
  declarations: [
    AppComponent,
    HelloWorldComponent,
    HelloWorldAutoGeneratedComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
